import type {
  Exam,
  Question,
  StudentHistoryItem,
  Submission,
} from "./types";

export const exams: Exam[] = [
  {
    id: "exam-1",
    title: "《数据结构》期中考试",
    description: "覆盖线性表、栈与队列、树与二叉树等章节，含客观题与简答题。",
    category: "计算机",
    durationMinutes: 60,
    questionCount: 8,
    totalScore: 100,
    status: "published",
    startAt: "2026-09-20T08:00:00.000Z",
    endAt: "2026-09-30T16:00:00.000Z",
    createdAt: "2026-09-18T10:00:00.000Z",
  },
  {
    id: "exam-2",
    title: "《计算机网络》单元测验（一）",
    description: "OSI 参考模型、TCP/IP 协议族与常见网络设备。",
    category: "计算机",
    durationMinutes: 45,
    questionCount: 4,
    totalScore: 100,
    status: "published",
    startAt: "2026-09-22T08:00:00.000Z",
    endAt: "2026-10-06T16:00:00.000Z",
    createdAt: "2026-09-19T09:30:00.000Z",
  },
  {
    id: "exam-3",
    title: "《高等数学》第 3 章 自测",
    description: "不定积分与定积分的计算与应用。",
    category: "数学",
    durationMinutes: 90,
    questionCount: 3,
    totalScore: 100,
    status: "published",
    startAt: "2026-10-01T00:00:00.000Z",
    endAt: "2026-10-15T16:00:00.000Z",
    createdAt: "2026-09-20T14:00:00.000Z",
  },
  {
    id: "exam-4",
    title: "《大学英语》四级模拟（阅读）",
    description: "阅读理解专项模拟，检验词汇与长难句理解能力。",
    category: "英语",
    durationMinutes: 40,
    questionCount: 5,
    totalScore: 100,
    status: "draft",
    startAt: "",
    endAt: "",
    createdAt: "2026-09-21T08:00:00.000Z",
  },
  {
    id: "exam-5",
    title: "《操作系统》期末模拟",
    description: "进程调度、内存管理与文件系统综合模拟。",
    category: "计算机",
    durationMinutes: 120,
    questionCount: 15,
    totalScore: 150,
    status: "closed",
    startAt: "2026-09-10T00:00:00.000Z",
    endAt: "2026-09-15T16:00:00.000Z",
    createdAt: "2026-09-08T10:00:00.000Z",
  },
];

export const questionBank: Question[] = [
  {
    id: "q-1",
    examId: "exam-1",
    type: "single",
    stem: "在长度为 n 的顺序表中插入一个元素，平均需要移动的元素个数是？",
    options: [
      { key: "A", text: "n" },
      { key: "B", text: "n/2" },
      { key: "C", text: "n-1" },
      { key: "D", text: "(n-1)/2" },
    ],
    answer: "B",
    score: 5,
    category: "数据结构",
    difficulty: "easy",
  },
  {
    id: "q-2",
    examId: "exam-1",
    type: "single",
    stem: "栈（Stack）的典型操作特征是？",
    options: [
      { key: "A", text: "先进先出" },
      { key: "B", text: "后进先出" },
      { key: "C", text: "随机访问" },
      { key: "D", text: "按优先级出队" },
    ],
    answer: "B",
    score: 5,
    category: "数据结构",
    difficulty: "easy",
  },
  {
    id: "q-3",
    examId: "exam-1",
    type: "judge",
    stem: "二叉树的先序遍历与中序遍历结果可以唯一确定一棵二叉树。",
    options: [
      { key: "T", text: "正确" },
      { key: "F", text: "错误" },
    ],
    answer: "T",
    score: 5,
    category: "数据结构",
    difficulty: "medium",
  },
  {
    id: "q-4",
    examId: "exam-1",
    type: "single",
    stem: "下列哪种数据结构属于非线性结构？",
    options: [
      { key: "A", text: "链表" },
      { key: "B", text: "栈" },
      { key: "C", text: "队列" },
      { key: "D", text: "树" },
    ],
    answer: "D",
    score: 10,
    category: "数据结构",
    difficulty: "medium",
  },
  {
    id: "q-5",
    examId: "exam-1",
    type: "single",
    stem: "快速排序的平均时间复杂度是？",
    options: [
      { key: "A", text: "O(n)" },
      { key: "B", text: "O(n log n)" },
      { key: "C", text: "O(n²)" },
      { key: "D", text: "O(log n)" },
    ],
    answer: "B",
    score: 5,
    category: "数据结构",
    difficulty: "medium",
  },
  {
    id: "q-6",
    examId: "exam-1",
    type: "single",
    stem: "队列（Queue）的典型操作特征是？",
    options: [
      { key: "A", text: "先进先出" },
      { key: "B", text: "后进先出" },
      { key: "C", text: "随机访问" },
      { key: "D", text: "只能从队头插入" },
    ],
    answer: "A",
    score: 10,
    category: "数据结构",
    difficulty: "medium",
  },
  {
    id: "q-7",
    examId: "exam-1",
    type: "judge",
    stem: "哈希表查找的平均时间复杂度可以达到 O(1)。",
    options: [
      { key: "T", text: "正确" },
      { key: "F", text: "错误" },
    ],
    answer: "T",
    score: 5,
    category: "数据结构",
    difficulty: "easy",
  },
  {
    id: "q-8",
    examId: "exam-1",
    type: "short",
    stem: "请简述「递归」的基本思想，并说明使用递归时需要注意的「两个基本要素」。",
    options: [],
    answer:
      "递归由「基线条件（递归出口）」和「递归关系（缩小问题规模）」两部分构成；需注意栈溢出与重复计算问题。",
    score: 55,
    category: "数据结构",
    difficulty: "hard",
  },
  {
    id: "q-9",
    examId: "exam-2",
    type: "single",
    stem: "TCP 协议位于 OSI 参考模型中的哪一层？",
    options: [
      { key: "A", text: "应用层" },
      { key: "B", text: "传输层" },
      { key: "C", text: "网络层" },
      { key: "D", text: "数据链路层" },
    ],
    answer: "B",
    score: 5,
    category: "计算机网络",
    difficulty: "easy",
  },
  {
    id: "q-10",
    examId: "exam-2",
    type: "single",
    stem: "IPv4 地址的长度是？",
    options: [
      { key: "A", text: "16 位" },
      { key: "B", text: "32 位" },
      { key: "C", text: "64 位" },
      { key: "D", text: "128 位" },
    ],
    answer: "B",
    score: 5,
    category: "计算机网络",
    difficulty: "easy",
  },
  {
    id: "q-11",
    examId: "exam-2",
    type: "judge",
    stem: "HTTP 默认使用 443 端口。",
    options: [
      { key: "T", text: "正确" },
      { key: "F", text: "错误" },
    ],
    answer: "F",
    score: 5,
    category: "计算机网络",
    difficulty: "easy",
  },
  {
    id: "q-12",
    examId: "exam-2",
    type: "short",
    stem: "简述 TCP 三次握手的过程。",
    options: [],
    answer: "SYN -> SYN+ACK -> ACK。",
    score: 20,
    category: "计算机网络",
    difficulty: "medium",
  },
  {
    id: "q-13",
    examId: "exam-3",
    type: "single",
    stem: "定积分 ∫₀¹ x dx 的值为？",
    options: [
      { key: "A", text: "0" },
      { key: "B", text: "1/2" },
      { key: "C", text: "1" },
      { key: "D", text: "2" },
    ],
    answer: "B",
    score: 10,
    category: "高等数学",
    difficulty: "medium",
  },
  {
    id: "q-14",
    type: "multiple",
    stem: "下列属于进程调度算法的有？（多选）",
    options: [
      { key: "A", text: "先来先服务 FCFS" },
      { key: "B", text: "最短作业优先 SJF" },
      { key: "C", text: "时间片轮转 RR" },
      { key: "D", text: "快速排序" },
    ],
    answer: ["A", "B", "C"],
    score: 10,
    category: "操作系统",
    difficulty: "medium",
  },
  {
    id: "q-15",
    examId: "exam-3",
    type: "single",
    stem: "函数 f(x) = x² 在 x = 1 处的导数是？",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "0" },
      { key: "D", text: "4" },
    ],
    answer: "B",
    score: 10,
    category: "高等数学",
    difficulty: "easy",
  },
  {
    id: "q-16",
    examId: "exam-3",
    type: "short",
    stem: "简述定积分的几何意义。",
    options: [],
    answer: "定积分表示曲边梯形的（带符号的）面积。",
    score: 30,
    category: "高等数学",
    difficulty: "medium",
  },
];

export const submissions: Submission[] = [
  {
    id: "sub-1",
    examId: "exam-1",
    examTitle: "《数据结构》期中考试",
    studentId: "stu-1001",
    studentName: "张伟",
    status: "reviewed",
    score: 88,
    totalScore: 100,
    submittedAt: "2026-09-21T09:42:00.000Z",
    durationUsed: "52 分钟",
  },
  {
    id: "sub-2",
    examId: "exam-1",
    examTitle: "《数据结构》期中考试",
    studentId: "stu-1002",
    studentName: "李娜",
    status: "pending_review",
    score: 76,
    totalScore: 100,
    submittedAt: "2026-09-21T10:05:00.000Z",
    durationUsed: "58 分钟",
  },
  {
    id: "sub-3",
    examId: "exam-1",
    examTitle: "《数据结构》期中考试",
    studentId: "stu-1003",
    studentName: "王强",
    status: "submitted",
    score: null,
    totalScore: 100,
    submittedAt: "2026-09-21T10:20:00.000Z",
    durationUsed: "47 分钟",
  },
  {
    id: "sub-4",
    examId: "exam-2",
    examTitle: "《计算机网络》单元测验（一）",
    studentId: "stu-1001",
    studentName: "张伟",
    status: "reviewed",
    score: 92,
    totalScore: 100,
    submittedAt: "2026-09-22T14:10:00.000Z",
    durationUsed: "38 分钟",
  },
  {
    id: "sub-5",
    examId: "exam-5",
    examTitle: "《操作系统》期末模拟",
    studentId: "stu-1004",
    studentName: "赵敏",
    status: "reviewed",
    score: 121,
    totalScore: 150,
    submittedAt: "2026-09-12T11:00:00.000Z",
    durationUsed: "105 分钟",
  },
  {
    id: "sub-6",
    examId: "exam-5",
    examTitle: "《操作系统》期末模拟",
    studentId: "stu-1005",
    studentName: "陈杰",
    status: "pending_review",
    score: 98,
    totalScore: 150,
    submittedAt: "2026-09-12T11:30:00.000Z",
    durationUsed: "112 分钟",
  },
  {
    id: "sub-7",
    examId: "exam-1",
    examTitle: "《数据结构》期中考试",
    studentId: "stu-1006",
    studentName: "刘洋",
    status: "in_progress",
    score: null,
    totalScore: 100,
    submittedAt: "",
    durationUsed: "进行中",
  },
];

export const studentHistory: StudentHistoryItem[] = [
  {
    examId: "exam-1",
    examTitle: "《数据结构》期中考试",
    submittedAt: "2026-09-21T09:42:00.000Z",
    status: "reviewed",
    score: 88,
    totalScore: 100,
    passed: true,
  },
  {
    examId: "exam-2",
    examTitle: "《计算机网络》单元测验（一）",
    submittedAt: "2026-09-22T14:10:00.000Z",
    status: "reviewed",
    score: 92,
    totalScore: 100,
    passed: true,
  },
  {
    examId: "exam-5",
    examTitle: "《操作系统》期末模拟",
    submittedAt: "2026-09-12T11:00:00.000Z",
    status: "pending_review",
    score: null,
    totalScore: 150,
    passed: null,
  },
  {
    examId: "exam-3",
    examTitle: "《高等数学》第 3 章 自测",
    submittedAt: "2026-09-02T16:20:00.000Z",
    status: "reviewed",
    score: 61,
    totalScore: 100,
    passed: false,
  },
];

export const adminStats = {
  examTotal: 5,
  publishedExams: 3,
  submissionTotal: 128,
  pendingReview: 23,
  averageScore: 78.5,
  passRate: 82.4,
};

export function getExamById(id: string): Exam | undefined {
  return exams.find((e) => e.id === id);
}

export function getQuestionsForExam(examId: string): Question[] {
  return questionBank.filter((q) => q.examId === examId);
}
